Repository SORSE/sorse.github.io, pull requests merged in 2020-06, with the labels that each got.

#74 Add FAQ to footer navigation
  _data/navigation.yml
Labels: layout

#77 Add git metadata to website
  .gitignore
  Gemfile
  _config.yml
  _includes/footer.html
  _includes/footer/custom.html
  assets/css/main.scss
Labels: layout

#119 allow multiple authors per topic summary
  _includes/topic-summary.html
Labels: layout, topic-bazaar

#121 Added text for talks team abstract FAQ
  _faq/talk/abstract.md
Labels: talks

#122 Added text for workshop team abstract FAQ
  _faq/workshop/abstract.md
Labels: workshop

#192 Twitter fix
  _config.yml
  _includes/seo.html
  _includes/twitter.html
  assets/images/sorse-banner-980x980.png
  assets/images/sorse-banner.png
Labels: layout
